language: node_js
node_js:
- '0.12'
before_install:
- npm install -g grunt-cli
install:
- npm install
before_script:
- grunt travis
script:
- grunt coveralls:dijit_coverage --verbose
after_success:

- git config --global user.email "sbatterby@esriuk.com"
- git config --global user.name "Travis CI"
- git clone https://github.com/EsriUK/wab-dijit-drilldown
- cp -r -v ${TRAVIS_BUILD_DIR}/build/* wab-dijit-drilldown/Drilldown/Drilldown/
- cd wab-dijit-drilldown
- git add -v Drilldown/\*
- git commit -m "Update from travis build of arcgis-dijit-drilldown"
- git push -v --force "https://${DEPLOY_KEY}@github.com/EsriUK/wab-dijit-drilldown" master
- echo -e "Done with magic\n"

env:
  global:
  - secure: YcB4wrv/RI6roxL65I/zIxp9fbfj9uKSGlv8e2akv7TaQ4KrqtLiqiYNcM75YmoCWgoLxuHWbu7fo0ybCesXCDcOzjN+BO5f/VUOCSFQuYeZzK2SJ6iMqBo/EknUG1Yv4uRDvoGPsjoDZXMvCI3OqK1McWMXF2CBep7jA5kc9P7ifMtGX+HU6v5+BlR6fYTjLRf+ddJF9bEpuC/WAMW2dGwjCb9/T0qVMS5dKkIANcLH1DcmaUR6LX84ov0evC4ztxAfxMj9S7U6N4i7iyT+Z6+b257ohYg1Ksz5fCS1g7PL3rNZEwtQc1l4h0Vh61wCaX636RXfA1l5zwEDuC/LteqyV0heW5LvqShW8XLbNYLbF6YbSFL3YgPIR//8gQl1hzE1+jCrxir7873WHXZANu0xrxVvPNtOAxFfMnJTmcLhhG5D5mx+eVqOzE5BfFVrOfhZoyqghi6HYolJ4ssyKIMNJTkFtnCEWWjOU2KvUWHSKYi8I8EntSV4coe9/HbGSzptVtM5WkIb/Ff0DJxKRKJcqrAmtCjcUVbTXqKChpzZ76oIRQ8GEA454rodEqzk2oqt9mD3DfMnuERIkUacVIbADAu9XveJWfiOZDXXLdpTSOzvlFDCQmM1QdDNlmjt/Tha1gmEQwGwirJYtJPR0vWwX2UjMndytzq2KD3esaQ=
  - secure: Ck0KpxXwMbaQcQ0qCyJ55TJLvcgSp94hwO3vhRxhXbQ79s33DzHj5o69MGMOLEGP6y8v/xHTSccmbEWm8/OdlhcIlMMHmDvEPT1FyKQwUUO9vX2TDy96tbprvIBaKJScdoAkMJLYDiGvXPhaWA/dVCNnT7YeNVj3UXB7IT3wM+HDuIJJInJuNYEOkdru8fm3VGHWwj0ZLMxiu9A1Wpjo9cK+i46Lhi7jqE6wpYX8RFToW9DiwSiE0wLuRbB6j1ZAD2VIHiYR0uqBjmk12r6S72eqdvWs5JlqKHw+OPagHczdTTdVpcCmNcVGfAc6JmWn00iIYt4/pL3dWjxkQRLZ7HoEyIHZSIE7I3nauC6tK/iEQH3W2MJ0/42BLXqqP+mL1eqiJ+HtuEIFBMeUCO7lSImeSzKyLvIJN11MgDcWz96Jn9CIsqDZBDCdYPhwa/qOLNM3jSGIRP7dr/D9PT2+4DX9RuEIKEz8jqTiCGhmGA0hKhzKpcleN8WmAdl/55ZuTKFFH/ZuhYlNb2QCoiRgBUi76RN8p8DwY983rYx8cM+ptdl+L5EWP/L5EQQvEf2omDMnOy0qQ6MOB/+wWAD6mxyQzYtmbLLHu9R0n0PLYX2XD7ugtmafKhUZ/3uFOXvmDfoFbWzwG5RqUy4qIcWvQ6bmHiRWSS47hLFFWYh2eu8=
  - secure: f2XwoVfRl7VZzwgA8Qn0xRMixJ63JGSEhyaA7gJQMHqixSlTAcX+quMGFQjFawQo183UMdSDuewSvwxfGoQn2qxTaIwrbtD6CFOPqWW6dgf+01KSmT2asVKu3GGcrHrMQPl9dgR1qGqP+FKuAMdjZz1S8KhAFTWYrQDs9CqTFcOuCaq4/4pU1KKAelV/QDjblowKwR9EN0s2vVeQs20FpG0h4zWF/91hKrEZb+6eLPXzi2OcFqyu+hdnbEOGugDRvoJkfcLsocX09AQr24bhNk9Yh7iPeA47XgG8QZG0WVhqUCtnPEsAN52HJi5SReevUWfcsYwd946fCo+Q2X9Cr3KkCVEBQ92x/53WuwJiGNz+sV+b+KIq6pWC2HtEq+MN1TOmJKJF4Cik3RGLIK5I6vRIWelIDAqxv0W/wnXpRWSQJK4nSH5Qra1GUVsR10QV2B2hN9yKkXyhf3mLvNH0NYfz8MIsDMt6Fnk4ZY5dT4ekmbKJqywdQ6xe+8wLe7cRdQE8ELhefPu3TnDaMgnGF8RJk9Uc2Ku8zmm5wxhAIj7ZSmUTJk/f1CjhELjuSnUioNfML146YHf6GtKGNZhqUXzLGi8TKOTVVoEod6qw9xx6UzznyqIMCjosSoQ9BRkRP0SNk0GQq5Z2bSnzEcKHY5djL6aGA/eydO6UJy7apfU=
