language: node_js
node_js:
  - "0.12"
before_install:
  - npm install -g grunt-cli
install: 
 - npm install
before_script: 
 - grunt travis
script: 
 - grunt coveralls:dijit_coverage --verbose
 addons:
  sauce_connect:
    username: "sbatterby"
    access_key: "fbaa5a4c-de4f-4969-8119-14eafd496572"
env:
  global:
    - secure: YcB4wrv/RI6roxL65I/zIxp9fbfj9uKSGlv8e2akv7TaQ4KrqtLiqiYNcM75YmoCWgoLxuHWbu7fo0ybCesXCDcOzjN+BO5f/VUOCSFQuYeZzK2SJ6iMqBo/EknUG1Yv4uRDvoGPsjoDZXMvCI3OqK1McWMXF2CBep7jA5kc9P7ifMtGX+HU6v5+BlR6fYTjLRf+ddJF9bEpuC/WAMW2dGwjCb9/T0qVMS5dKkIANcLH1DcmaUR6LX84ov0evC4ztxAfxMj9S7U6N4i7iyT+Z6+b257ohYg1Ksz5fCS1g7PL3rNZEwtQc1l4h0Vh61wCaX636RXfA1l5zwEDuC/LteqyV0heW5LvqShW8XLbNYLbF6YbSFL3YgPIR//8gQl1hzE1+jCrxir7873WHXZANu0xrxVvPNtOAxFfMnJTmcLhhG5D5mx+eVqOzE5BfFVrOfhZoyqghi6HYolJ4ssyKIMNJTkFtnCEWWjOU2KvUWHSKYi8I8EntSV4coe9/HbGSzptVtM5WkIb/Ff0DJxKRKJcqrAmtCjcUVbTXqKChpzZ76oIRQ8GEA454rodEqzk2oqt9mD3DfMnuERIkUacVIbADAu9XveJWfiOZDXXLdpTSOzvlFDCQmM1QdDNlmjt/Tha1gmEQwGwirJYtJPR0vWwX2UjMndytzq2KD3esaQ=
    - secure: Ck0KpxXwMbaQcQ0qCyJ55TJLvcgSp94hwO3vhRxhXbQ79s33DzHj5o69MGMOLEGP6y8v/xHTSccmbEWm8/OdlhcIlMMHmDvEPT1FyKQwUUO9vX2TDy96tbprvIBaKJScdoAkMJLYDiGvXPhaWA/dVCNnT7YeNVj3UXB7IT3wM+HDuIJJInJuNYEOkdru8fm3VGHWwj0ZLMxiu9A1Wpjo9cK+i46Lhi7jqE6wpYX8RFToW9DiwSiE0wLuRbB6j1ZAD2VIHiYR0uqBjmk12r6S72eqdvWs5JlqKHw+OPagHczdTTdVpcCmNcVGfAc6JmWn00iIYt4/pL3dWjxkQRLZ7HoEyIHZSIE7I3nauC6tK/iEQH3W2MJ0/42BLXqqP+mL1eqiJ+HtuEIFBMeUCO7lSImeSzKyLvIJN11MgDcWz96Jn9CIsqDZBDCdYPhwa/qOLNM3jSGIRP7dr/D9PT2+4DX9RuEIKEz8jqTiCGhmGA0hKhzKpcleN8WmAdl/55ZuTKFFH/ZuhYlNb2QCoiRgBUi76RN8p8DwY983rYx8cM+ptdl+L5EWP/L5EQQvEf2omDMnOy0qQ6MOB/+wWAD6mxyQzYtmbLLHu9R0n0PLYX2XD7ugtmafKhUZ/3uFOXvmDfoFbWzwG5RqUy4qIcWvQ6bmHiRWSS47hLFFWYh2eu8=