var singleLevelMulti = {
    "PickListItems": [{
        "Description": "CORSTORPHINE HIGH STREET, EDINBURGH, CITY OF EDINBURGH",
        "Addresses": [
            {
                "Description": "23, CORSTORPHINE HIGH STREET, EDINBURGH, CITY OF EDINBURGH",
                "Addresses": [
                    {
                        "address": "23 CORSTORPHINE HIGH STREET, EDINBURGH, CITY OF EDINBURGH",
                        "location": {
                            "x": 319923,
                            "y": 672680
                        },
                        "score": 100,
                        "attributes": {
                            "Match_addr": "23 CORSTORPHINE HIGH STREET, EDINBURGH, CITY OF EDINBURGH",
                            "Addr_type": "Address",
                            "LOCATOR_ENVELOPE": "319923,672680,319923,672680",
                            "LOCATOR_POINT": "319923,672680",
                            "LOCATOR_DESCRIPTION": "23 CORSTORPHINE HIGH STREET, EDINBURGH, CITY OF EDINBURGH",
                            "LOCATOR_FAMILY_ID": "906389493",
                            "LOCATOR_ID": "114717",
                            "LOCATOR_DATASET_ID": "9064L000208965:ENG",
                            "LOCATOR_DATASET_FAMILY_ID": "906389493",
                            "LOCATOR_RESOLUTION": 90,
                            "LOCATOR_SCORE": 100,
                            "UPRN": "906389493",
                            "BLPU_LOGICAL_STATUS": 1,
                            "BLPU_STATE": 2,
                            "BLPU_STATE_DATE": "3/1/1991 12:00:00 AM",
                            "PARENT_UPRN": "",
                            "RPA": 1,
                            "LOCAL_CUSTODIAN_CODE": 9064,
                            "BLPU_START_DATE": "3/1/1991 12:00:00 AM",
                            "BLPU_END_DATE": null,
                            "BLPU_LAST_UPDATE_DATE": "12/19/2011 12:00:00 AM",
                            "BLPU_ENTRY_DATE": "3/1/1991 12:00:00 AM",
                            "ORGANISATION": "",
                            "BLPU_CLASS": "PP",
                            "WARD_CODE": "",
                            "PARISH_CODE": "",
                            "BLPU_CUSTODIAN_ONE": null,
                            "BLPU_CUSTODIAN_TWO": null,
                            "LPI_KEY": "9064L000208965",
                            "LPI_LANGUAGE": "ENG",
                            "LPI_LOGICAL_STATUS": 1,
                            "LPI_START_DATE": "3/1/1991 12:00:00 AM",
                            "LPI_END_DATE": null,
                            "LPI_LAST_UPDATE_DATE": "9/28/2011 12:00:00 AM",
                            "LPI_ENTRY_DATE": "3/1/1991 12:00:00 AM",
                            "SAO_START_NUMBER": "",
                            "SAO_END_NUMBER": "",
                            "SAO_START_SUFFIX": "",
                            "SAO_END_SUFFIX": "",
                            "SAO_TEXT": "",
                            "PAO_START_NUMBER": "23",
                            "PAO_END_NUMBER": "",
                            "PAO_START_SUFFIX": "",
                            "PAO_END_SUFFIX": "",
                            "PAO_TEXT": "",
                            "LEVEL": "",
                            "POSTALLY_ADDRESSABLE": "N",
                            "POSTCODE": "",
                            "POST_TOWN": "",
                            "OFFICIAL_FLAG": "Y",
                            "LPI_CUSTODIAN_ONE": null,
                            "LPI_CUSTODIAN_TWO": null,
                            "STREET_RECORD_TYPE": 1,
                            "SWA_ORG_REF_NAMING": 9064,
                            "STREET_STATE": null,
                            "STREET_STATE_DATE": "1/4/1996 12:00:00 AM",
                            "STREET_SURFACE": 1,
                            "STREET_CLASSIFICATION": 8,
                            "STREET_VERSION": 0,
                            "STREET_LAST_UPDATE_DATE": "1/28/2009 12:00:00 AM",
                            "STREET_START_DATE": null,
                            "STREET_END_DATE": null,
                            "STREET_TOLERANCE": 1,
                            "STREET_START_X": 320017,
                            "STREET_START_Y": 672711,
                            "STREET_END_X": 319688,
                            "STREET_END_Y": 672642,
                            "STREET_DESCRIPTOR": "CORSTORPHINE HIGH STREET",
                            "LOCALITY_NAME": "",
                            "ADMINISTRATIVE_AREA": "CITY OF EDINBURGH",
                            "TOWN_NAME": "EDINBURGH",
                            "STREET_LANGUAGE": "ENG",
                            "USRN": "7902692"
                        },
                        "SortDescription": ""
                    },
                    {
                        "address": "1F1, 23 CORSTORPHINE HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH12 7SU",
                        "location": {
                            "x": 319923,
                            "y": 672680
                        },
                        "score": 100,
                        "attributes": {
                            "Match_addr": "1F1, 23 CORSTORPHINE HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH12 7SU",
                            "Addr_type": "Address",
                            "LOCATOR_ENVELOPE": "319923,672680,319923,672680",
                            "LOCATOR_POINT": "319923,672680",
                            "LOCATOR_DESCRIPTION": "1F1, 23 CORSTORPHINE HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH12 7SU",
                            "LOCATOR_FAMILY_ID": "906291869",
                            "LOCATOR_ID": "261672",
                            "LOCATOR_DATASET_ID": "9064L000068299:ENG",
                            "LOCATOR_DATASET_FAMILY_ID": "906291869",
                            "LOCATOR_RESOLUTION": 90,
                            "LOCATOR_SCORE": 100,
                            "UPRN": "906291869",
                            "BLPU_LOGICAL_STATUS": 1,
                            "BLPU_STATE": 2,
                            "BLPU_STATE_DATE": "3/1/1991 12:00:00 AM",
                            "PARENT_UPRN": "906389493",
                            "RPA": 1,
                            "LOCAL_CUSTODIAN_CODE": 9064,
                            "BLPU_START_DATE": "3/1/1991 12:00:00 AM",
                            "BLPU_END_DATE": null,
                            "BLPU_LAST_UPDATE_DATE": "3/1/1991 12:00:00 AM",
                            "BLPU_ENTRY_DATE": "3/1/1991 12:00:00 AM",
                            "ORGANISATION": "",
                            "BLPU_CLASS": "RD",
                            "WARD_CODE": "",
                            "PARISH_CODE": "",
                            "BLPU_CUSTODIAN_ONE": null,
                            "BLPU_CUSTODIAN_TWO": null,
                            "LPI_KEY": "9064L000068299",
                            "LPI_LANGUAGE": "ENG",
                            "LPI_LOGICAL_STATUS": 1,
                            "LPI_START_DATE": "3/1/1991 12:00:00 AM",
                            "LPI_END_DATE": null,
                            "LPI_LAST_UPDATE_DATE": "9/28/2011 12:00:00 AM",
                            "LPI_ENTRY_DATE": "3/1/1991 12:00:00 AM",
                            "SAO_START_NUMBER": "",
                            "SAO_END_NUMBER": "",
                            "SAO_START_SUFFIX": "",
                            "SAO_END_SUFFIX": "",
                            "SAO_TEXT": "1F1",
                            "PAO_START_NUMBER": "23",
                            "PAO_END_NUMBER": "",
                            "PAO_START_SUFFIX": "",
                            "PAO_END_SUFFIX": "",
                            "PAO_TEXT": "",
                            "LEVEL": "",
                            "POSTALLY_ADDRESSABLE": "Y",
                            "POSTCODE": "EH12 7SU",
                            "POST_TOWN": "EDINBURGH",
                            "OFFICIAL_FLAG": "Y",
                            "LPI_CUSTODIAN_ONE": null,
                            "LPI_CUSTODIAN_TWO": null,
                            "STREET_RECORD_TYPE": 1,
                            "SWA_ORG_REF_NAMING": 9064,
                            "STREET_STATE": null,
                            "STREET_STATE_DATE": "1/4/1996 12:00:00 AM",
                            "STREET_SURFACE": 1,
                            "STREET_CLASSIFICATION": 8,
                            "STREET_VERSION": 0,
                            "STREET_LAST_UPDATE_DATE": "1/28/2009 12:00:00 AM",
                            "STREET_START_DATE": null,
                            "STREET_END_DATE": null,
                            "STREET_TOLERANCE": 1,
                            "STREET_START_X": 320017,
                            "STREET_START_Y": 672711,
                            "STREET_END_X": 319688,
                            "STREET_END_Y": 672642,
                            "STREET_DESCRIPTOR": "CORSTORPHINE HIGH STREET",
                            "LOCALITY_NAME": "",
                            "ADMINISTRATIVE_AREA": "CITY OF EDINBURGH",
                            "TOWN_NAME": "EDINBURGH",
                            "STREET_LANGUAGE": "ENG",
                            "USRN": "7902692"
                        },
                        "SortDescription": "1F1"
                    },
                    {
                        "address": "1F2, 23 CORSTORPHINE HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH12 7SU",
                        "location": {
                            "x": 319923,
                            "y": 672680
                        },
                        "score": 100,
                        "attributes": {
                            "Match_addr": "1F2, 23 CORSTORPHINE HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH12 7SU",
                            "Addr_type": "Address",
                            "LOCATOR_ENVELOPE": "319923,672680,319923,672680",
                            "LOCATOR_POINT": "319923,672680",
                            "LOCATOR_DESCRIPTION": "1F2, 23 CORSTORPHINE HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH12 7SU",
                            "LOCATOR_FAMILY_ID": "906291870",
                            "LOCATOR_ID": "261673",
                            "LOCATOR_DATASET_ID": "9064L000068300:ENG",
                            "LOCATOR_DATASET_FAMILY_ID": "906291870",
                            "LOCATOR_RESOLUTION": 90,
                            "LOCATOR_SCORE": 100,
                            "UPRN": "906291870",
                            "BLPU_LOGICAL_STATUS": 1,
                            "BLPU_STATE": 2,
                            "BLPU_STATE_DATE": "3/1/1991 12:00:00 AM",
                            "PARENT_UPRN": "906389493",
                            "RPA": 1,
                            "LOCAL_CUSTODIAN_CODE": 9064,
                            "BLPU_START_DATE": "3/1/1991 12:00:00 AM",
                            "BLPU_END_DATE": null,
                            "BLPU_LAST_UPDATE_DATE": "3/1/1991 12:00:00 AM",
                            "BLPU_ENTRY_DATE": "3/1/1991 12:00:00 AM",
                            "ORGANISATION": "",
                            "BLPU_CLASS": "RD",
                            "WARD_CODE": "",
                            "PARISH_CODE": "",
                            "BLPU_CUSTODIAN_ONE": null,
                            "BLPU_CUSTODIAN_TWO": null,
                            "LPI_KEY": "9064L000068300",
                            "LPI_LANGUAGE": "ENG",
                            "LPI_LOGICAL_STATUS": 1,
                            "LPI_START_DATE": "3/1/1991 12:00:00 AM",
                            "LPI_END_DATE": null,
                            "LPI_LAST_UPDATE_DATE": "9/28/2011 12:00:00 AM",
                            "LPI_ENTRY_DATE": "3/1/1991 12:00:00 AM",
                            "SAO_START_NUMBER": "",
                            "SAO_END_NUMBER": "",
                            "SAO_START_SUFFIX": "",
                            "SAO_END_SUFFIX": "",
                            "SAO_TEXT": "1F2",
                            "PAO_START_NUMBER": "23",
                            "PAO_END_NUMBER": "",
                            "PAO_START_SUFFIX": "",
                            "PAO_END_SUFFIX": "",
                            "PAO_TEXT": "",
                            "LEVEL": "",
                            "POSTALLY_ADDRESSABLE": "Y",
                            "POSTCODE": "EH12 7SU",
                            "POST_TOWN": "EDINBURGH",
                            "OFFICIAL_FLAG": "Y",
                            "LPI_CUSTODIAN_ONE": null,
                            "LPI_CUSTODIAN_TWO": null,
                            "STREET_RECORD_TYPE": 1,
                            "SWA_ORG_REF_NAMING": 9064,
                            "STREET_STATE": null,
                            "STREET_STATE_DATE": "1/4/1996 12:00:00 AM",
                            "STREET_SURFACE": 1,
                            "STREET_CLASSIFICATION": 8,
                            "STREET_VERSION": 0,
                            "STREET_LAST_UPDATE_DATE": "1/28/2009 12:00:00 AM",
                            "STREET_START_DATE": null,
                            "STREET_END_DATE": null,
                            "STREET_TOLERANCE": 1,
                            "STREET_START_X": 320017,
                            "STREET_START_Y": 672711,
                            "STREET_END_X": 319688,
                            "STREET_END_Y": 672642,
                            "STREET_DESCRIPTOR": "CORSTORPHINE HIGH STREET",
                            "LOCALITY_NAME": "",
                            "ADMINISTRATIVE_AREA": "CITY OF EDINBURGH",
                            "TOWN_NAME": "EDINBURGH",
                            "STREET_LANGUAGE": "ENG",
                            "USRN": "7902692"
                        },
                        "SortDescription": "1F2"
                    }
                ],
                "Level": 1,
                "SortDescription": "23"
            }
        ],
        "Level": 0,
        "SortDescription": ""
    }
        
            
    ]
};

var singleResult = {
    "PickListItems": [
        {
            "Description": "HARRISON ROAD, EDINBURGH, CITY OF EDINBURGH",
            "Addresses": [
                {
                    "address": "7 HARRISON ROAD, EDINBURGH, CITY OF EDINBURGH, EH11 1EG",
                    "location": {
                        "x": 323482,
                        "y": 672206
                    },
                    "score": 100,
                    "attributes": {
                        "Match_addr": "7 HARRISON ROAD, EDINBURGH, CITY OF EDINBURGH, EH11 1EG",
                        "Addr_type": "Address",
                        "LOCATOR_ENVELOPE": "323482,672206,323482,672206",
                        "LOCATOR_POINT": "323482,672206",
                        "LOCATOR_DESCRIPTION": "7 HARRISON ROAD, EDINBURGH, CITY OF EDINBURGH, EH11 1EG",
                        "LOCATOR_FAMILY_ID": "906121539",
                        "LOCATOR_ID": "176802",
                        "LOCATOR_DATASET_ID": "9064L000149727:ENG",
                        "LOCATOR_DATASET_FAMILY_ID": "906121539",
                        "LOCATOR_RESOLUTION": 90,
                        "LOCATOR_SCORE": 100,
                        "UPRN": "906121539",
                        "BLPU_LOGICAL_STATUS": 1,
                        "BLPU_STATE": 2,
                        "BLPU_STATE_DATE": "3/1/1991 12:00:00 AM",
                        "PARENT_UPRN": "",
                        "RPA": 1,
                        "LOCAL_CUSTODIAN_CODE": 9064,
                        "BLPU_START_DATE": "3/1/1991 12:00:00 AM",
                        "BLPU_END_DATE": null,
                        "BLPU_LAST_UPDATE_DATE": "3/1/1991 12:00:00 AM",
                        "BLPU_ENTRY_DATE": "3/1/1991 12:00:00 AM",
                        "ORGANISATION": "",
                        "BLPU_CLASS": "RD",
                        "WARD_CODE": "",
                        "PARISH_CODE": "",
                        "BLPU_CUSTODIAN_ONE": null,
                        "BLPU_CUSTODIAN_TWO": null,
                        "LPI_KEY": "9064L000149727",
                        "LPI_LANGUAGE": "ENG",
                        "LPI_LOGICAL_STATUS": 1,
                        "LPI_START_DATE": "3/1/1991 12:00:00 AM",
                        "LPI_END_DATE": null,
                        "LPI_LAST_UPDATE_DATE": "9/30/2011 12:00:00 AM",
                        "LPI_ENTRY_DATE": "3/1/1991 12:00:00 AM",
                        "SAO_START_NUMBER": "",
                        "SAO_END_NUMBER": "",
                        "SAO_START_SUFFIX": "",
                        "SAO_END_SUFFIX": "",
                        "SAO_TEXT": "",
                        "PAO_START_NUMBER": "7",
                        "PAO_END_NUMBER": "",
                        "PAO_START_SUFFIX": "",
                        "PAO_END_SUFFIX": "",
                        "PAO_TEXT": "",
                        "LEVEL": "",
                        "POSTALLY_ADDRESSABLE": "Y",
                        "POSTCODE": "EH11 1EG",
                        "POST_TOWN": "EDINBURGH",
                        "OFFICIAL_FLAG": "Y",
                        "LPI_CUSTODIAN_ONE": null,
                        "LPI_CUSTODIAN_TWO": null,
                        "STREET_RECORD_TYPE": 1,
                        "SWA_ORG_REF_NAMING": 9064,
                        "STREET_STATE": null,
                        "STREET_STATE_DATE": "1/4/1996 12:00:00 AM",
                        "STREET_SURFACE": 1,
                        "STREET_CLASSIFICATION": 8,
                        "STREET_VERSION": 0,
                        "STREET_LAST_UPDATE_DATE": "1/28/2009 12:00:00 AM",
                        "STREET_START_DATE": null,
                        "STREET_END_DATE": null,
                        "STREET_TOLERANCE": 1,
                        "STREET_START_X": 323480,
                        "STREET_START_Y": 672257,
                        "STREET_END_X": 323655,
                        "STREET_END_Y": 671848,
                        "STREET_DESCRIPTOR": "HARRISON ROAD",
                        "LOCALITY_NAME": "",
                        "ADMINISTRATIVE_AREA": "CITY OF EDINBURGH",
                        "TOWN_NAME": "EDINBURGH",
                        "STREET_LANGUAGE": "ENG",
                        "USRN": "7902903"
                    }
                }
            ],
            "Level": 2,
            "SortDescription": "HARRISON ROAD"
        }
    ]
};


var postcodeResults = {
    "PickListItems": [
        {
            "Description": "HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH",
            "Addresses": [
                {
                    "Description": "106, HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH",
                    "Addresses": [
                        {
                            "address": "1F-2F, 106 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                            "location": {
                                "x": 326605,
                                "y": 673666
                            },
                            "score": 100,
                            "attributes": {
                                "Match_addr": "1F-2F, 106 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                                "Addr_type": "Address",
                                "LOCATOR_ENVELOPE": "326605,673666,326605,673666",
                                "LOCATOR_POINT": "326605,673666",
                                "LOCATOR_DESCRIPTION": "1F-2F, 106 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                                "LOCATOR_FAMILY_ID": "906440082",
                                "LOCATOR_ID": "47784",
                                "LOCATOR_DATASET_ID": "9064L000239174:ENG",
                                "LOCATOR_DATASET_FAMILY_ID": "906440082",
                                "LOCATOR_RESOLUTION": 90,
                                "LOCATOR_SCORE": 100,
                                "UPRN": "906440082",
                                "BLPU_LOGICAL_STATUS": 1,
                                "BLPU_STATE": 2,
                                "BLPU_STATE_DATE": "2/20/2007 12:00:00 AM",
                                "PARENT_UPRN": "906421889",
                                "RPA": 1,
                                "LOCAL_CUSTODIAN_CODE": 9064,
                                "BLPU_START_DATE": "2/20/2007 12:00:00 AM",
                                "BLPU_END_DATE": null,
                                "BLPU_LAST_UPDATE_DATE": "2/20/2007 12:00:00 AM",
                                "BLPU_ENTRY_DATE": "2/20/2007 12:00:00 AM",
                                "ORGANISATION": "",
                                "BLPU_CLASS": "C",
                                "WARD_CODE": "",
                                "PARISH_CODE": "",
                                "BLPU_CUSTODIAN_ONE": null,
                                "BLPU_CUSTODIAN_TWO": null,
                                "LPI_KEY": "9064L000239174",
                                "LPI_LANGUAGE": "ENG",
                                "LPI_LOGICAL_STATUS": 1,
                                "LPI_START_DATE": "2/20/2007 12:00:00 AM",
                                "LPI_END_DATE": null,
                                "LPI_LAST_UPDATE_DATE": "11/2/2011 12:00:00 AM",
                                "LPI_ENTRY_DATE": "2/20/2007 12:00:00 AM",
                                "SAO_START_NUMBER": "1",
                                "SAO_END_NUMBER": "2",
                                "SAO_START_SUFFIX": "F",
                                "SAO_END_SUFFIX": "F",
                                "SAO_TEXT": "",
                                "PAO_START_NUMBER": "106",
                                "PAO_END_NUMBER": "",
                                "PAO_START_SUFFIX": "",
                                "PAO_END_SUFFIX": "",
                                "PAO_TEXT": "",
                                "LEVEL": "",
                                "POSTALLY_ADDRESSABLE": "Y",
                                "POSTCODE": "EH8 8AS",
                                "POST_TOWN": "EDINBURGH",
                                "OFFICIAL_FLAG": "Y",
                                "LPI_CUSTODIAN_ONE": null,
                                "LPI_CUSTODIAN_TWO": null,
                                "STREET_RECORD_TYPE": 1,
                                "SWA_ORG_REF_NAMING": 9064,
                                "STREET_STATE": null,
                                "STREET_STATE_DATE": "11/27/1995 12:00:00 AM",
                                "STREET_SURFACE": 1,
                                "STREET_CLASSIFICATION": 8,
                                "STREET_VERSION": 0,
                                "STREET_LAST_UPDATE_DATE": "1/28/2009 12:00:00 AM",
                                "STREET_START_DATE": null,
                                "STREET_END_DATE": null,
                                "STREET_TOLERANCE": 1,
                                "STREET_START_X": 326711,
                                "STREET_START_Y": 673773,
                                "STREET_END_X": 326208,
                                "STREET_END_Y": 673543,
                                "STREET_DESCRIPTOR": "HOLYROOD ROAD",
                                "LOCALITY_NAME": "",
                                "ADMINISTRATIVE_AREA": "CITY OF EDINBURGH",
                                "TOWN_NAME": "EDINBURGH",
                                "STREET_LANGUAGE": "ENG",
                                "USRN": "7901866"
                            },
                            "SortDescription": "1F-2F"
                        },
                        {
                            "address": "GF1, 106 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                            "location": {
                                "x": 326605,
                                "y": 673666
                            },
                            "score": 100,
                            "attributes": {
                                "Match_addr": "GF1, 106 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                                "Addr_type": "Address",
                                "LOCATOR_ENVELOPE": "326605,673666,326605,673666",
                                "LOCATOR_POINT": "326605,673666",
                                "LOCATOR_DESCRIPTION": "GF1, 106 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                                "LOCATOR_FAMILY_ID": "906461856",
                                "LOCATOR_ID": "41742",
                                "LOCATOR_DATASET_ID": "9064L000243911:ENG",
                                "LOCATOR_DATASET_FAMILY_ID": "906461856",
                                "LOCATOR_RESOLUTION": 90,
                                "LOCATOR_SCORE": 100,
                                "UPRN": "906461856",
                                "BLPU_LOGICAL_STATUS": 1,
                                "BLPU_STATE": 2,
                                "BLPU_STATE_DATE": "5/13/2008 12:00:00 AM",
                                "PARENT_UPRN": "906421889",
                                "RPA": 1,
                                "LOCAL_CUSTODIAN_CODE": 9064,
                                "BLPU_START_DATE": "5/13/2008 12:00:00 AM",
                                "BLPU_END_DATE": null,
                                "BLPU_LAST_UPDATE_DATE": "5/13/2008 12:00:00 AM",
                                "BLPU_ENTRY_DATE": "5/13/2008 12:00:00 AM",
                                "ORGANISATION": "",
                                "BLPU_CLASS": "C",
                                "WARD_CODE": "",
                                "PARISH_CODE": "",
                                "BLPU_CUSTODIAN_ONE": null,
                                "BLPU_CUSTODIAN_TWO": null,
                                "LPI_KEY": "9064L000243911",
                                "LPI_LANGUAGE": "ENG",
                                "LPI_LOGICAL_STATUS": 1,
                                "LPI_START_DATE": "5/13/2008 12:00:00 AM",
                                "LPI_END_DATE": null,
                                "LPI_LAST_UPDATE_DATE": "10/5/2011 12:00:00 AM",
                                "LPI_ENTRY_DATE": "5/13/2008 12:00:00 AM",
                                "SAO_START_NUMBER": "",
                                "SAO_END_NUMBER": "",
                                "SAO_START_SUFFIX": "",
                                "SAO_END_SUFFIX": "",
                                "SAO_TEXT": "GF1",
                                "PAO_START_NUMBER": "106",
                                "PAO_END_NUMBER": "",
                                "PAO_START_SUFFIX": "",
                                "PAO_END_SUFFIX": "",
                                "PAO_TEXT": "",
                                "LEVEL": "",
                                "POSTALLY_ADDRESSABLE": "Y",
                                "POSTCODE": "EH8 8AS",
                                "POST_TOWN": "EDINBURGH",
                                "OFFICIAL_FLAG": "Y",
                                "LPI_CUSTODIAN_ONE": null,
                                "LPI_CUSTODIAN_TWO": null,
                                "STREET_RECORD_TYPE": 1,
                                "SWA_ORG_REF_NAMING": 9064,
                                "STREET_STATE": null,
                                "STREET_STATE_DATE": "11/27/1995 12:00:00 AM",
                                "STREET_SURFACE": 1,
                                "STREET_CLASSIFICATION": 8,
                                "STREET_VERSION": 0,
                                "STREET_LAST_UPDATE_DATE": "1/28/2009 12:00:00 AM",
                                "STREET_START_DATE": null,
                                "STREET_END_DATE": null,
                                "STREET_TOLERANCE": 1,
                                "STREET_START_X": 326711,
                                "STREET_START_Y": 673773,
                                "STREET_END_X": 326208,
                                "STREET_END_Y": 673543,
                                "STREET_DESCRIPTOR": "HOLYROOD ROAD",
                                "LOCALITY_NAME": "",
                                "ADMINISTRATIVE_AREA": "CITY OF EDINBURGH",
                                "TOWN_NAME": "EDINBURGH",
                                "STREET_LANGUAGE": "ENG",
                                "USRN": "7901866"
                            },
                            "SortDescription": "GF1"
                        }
                    ],
                    "Level": 1,
                    "SortDescription": "108"
                },
                {
                    "Description": "110, HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH",
                    "Addresses": [
                        {
                            "address": "110 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                            "location": {
                                "x": 326768,
                                "y": 673679
                            },
                            "score": 100,
                            "attributes": {
                                "Match_addr": "110 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                                "Addr_type": "Address",
                                "LOCATOR_ENVELOPE": "326768,673679,326768,673679",
                                "LOCATOR_POINT": "326768,673679",
                                "LOCATOR_DESCRIPTION": "110 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                                "LOCATOR_FAMILY_ID": "906382849",
                                "LOCATOR_ID": "320913",
                                "LOCATOR_DATASET_ID": "9064L000006149:ENG",
                                "LOCATOR_DATASET_FAMILY_ID": "906382849",
                                "LOCATOR_RESOLUTION": 90,
                                "LOCATOR_SCORE": 100,
                                "UPRN": "906382849",
                                "BLPU_LOGICAL_STATUS": 1,
                                "BLPU_STATE": 2,
                                "BLPU_STATE_DATE": "11/13/2001 12:00:00 AM",
                                "PARENT_UPRN": "",
                                "RPA": 1,
                                "LOCAL_CUSTODIAN_CODE": 9064,
                                "BLPU_START_DATE": "11/13/2001 12:00:00 AM",
                                "BLPU_END_DATE": null,
                                "BLPU_LAST_UPDATE_DATE": "5/11/2005 12:00:00 AM",
                                "BLPU_ENTRY_DATE": "11/13/2001 12:00:00 AM",
                                "ORGANISATION": "",
                                "BLPU_CLASS": "C",
                                "WARD_CODE": "",
                                "PARISH_CODE": "",
                                "BLPU_CUSTODIAN_ONE": null,
                                "BLPU_CUSTODIAN_TWO": null,
                                "LPI_KEY": "9064L000006149",
                                "LPI_LANGUAGE": "ENG",
                                "LPI_LOGICAL_STATUS": 1,
                                "LPI_START_DATE": "11/13/2001 12:00:00 AM",
                                "LPI_END_DATE": null,
                                "LPI_LAST_UPDATE_DATE": "9/29/2011 12:00:00 AM",
                                "LPI_ENTRY_DATE": "11/13/2001 12:00:00 AM",
                                "SAO_START_NUMBER": "",
                                "SAO_END_NUMBER": "",
                                "SAO_START_SUFFIX": "",
                                "SAO_END_SUFFIX": "",
                                "SAO_TEXT": "",
                                "PAO_START_NUMBER": "110",
                                "PAO_END_NUMBER": "",
                                "PAO_START_SUFFIX": "",
                                "PAO_END_SUFFIX": "",
                                "PAO_TEXT": "",
                                "LEVEL": "",
                                "POSTALLY_ADDRESSABLE": "Y",
                                "POSTCODE": "EH8 8AS",
                                "POST_TOWN": "EDINBURGH",
                                "OFFICIAL_FLAG": "Y",
                                "LPI_CUSTODIAN_ONE": null,
                                "LPI_CUSTODIAN_TWO": null,
                                "STREET_RECORD_TYPE": 1,
                                "SWA_ORG_REF_NAMING": 9064,
                                "STREET_STATE": null,
                                "STREET_STATE_DATE": "11/27/1995 12:00:00 AM",
                                "STREET_SURFACE": 1,
                                "STREET_CLASSIFICATION": 8,
                                "STREET_VERSION": 0,
                                "STREET_LAST_UPDATE_DATE": "1/28/2009 12:00:00 AM",
                                "STREET_START_DATE": null,
                                "STREET_END_DATE": null,
                                "STREET_TOLERANCE": 1,
                                "STREET_START_X": 326711,
                                "STREET_START_Y": 673773,
                                "STREET_END_X": 326208,
                                "STREET_END_Y": 673543,
                                "STREET_DESCRIPTOR": "HOLYROOD ROAD",
                                "LOCALITY_NAME": "",
                                "ADMINISTRATIVE_AREA": "CITY OF EDINBURGH",
                                "TOWN_NAME": "EDINBURGH",
                                "STREET_LANGUAGE": "ENG",
                                "USRN": "7901866"
                            },
                            "SortDescription": ""
                        }
                    ],
                    "Level": 1,
                    "SortDescription": "110"
                },
                {
                    "Description": "111, HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH",
                    "Addresses": [
                        {
                            "address": "111 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                            "location": {
                                "x": 326672,
                                "y": 673739
                            },
                            "score": 100,
                            "attributes": {
                                "Match_addr": "111 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                                "Addr_type": "Address",
                                "LOCATOR_ENVELOPE": "326672,673739,326672,673739",
                                "LOCATOR_POINT": "326672,673739",
                                "LOCATOR_DESCRIPTION": "111 HOLYROOD ROAD, EDINBURGH, CITY OF EDINBURGH, EH8 8AS",
                                "LOCATOR_FAMILY_ID": "906360091",
                                "LOCATOR_ID": "311251",
                                "LOCATOR_DATASET_ID": "9064L000016586:ENG",
                                "LOCATOR_DATASET_FAMILY_ID": "906360091",
                                "LOCATOR_RESOLUTION": 90,
                                "LOCATOR_SCORE": 100,
                                "UPRN": "906360091",
                                "BLPU_LOGICAL_STATUS": 1,
                                "BLPU_STATE": 2,
                                "BLPU_STATE_DATE": "9/15/1992 12:00:00 AM",
                                "PARENT_UPRN": "",
                                "RPA": 1,
                                "LOCAL_CUSTODIAN_CODE": 9064,
                                "BLPU_START_DATE": "9/15/1992 12:00:00 AM",
                                "BLPU_END_DATE": null,
                                "BLPU_LAST_UPDATE_DATE": "9/9/2011 12:00:00 AM",
                                "BLPU_ENTRY_DATE": "9/15/1992 12:00:00 AM",
                                "ORGANISATION": "",
                                "BLPU_CLASS": "C",
                                "WARD_CODE": "",
                                "PARISH_CODE": "",
                                "BLPU_CUSTODIAN_ONE": null,
                                "BLPU_CUSTODIAN_TWO": null,
                                "LPI_KEY": "9064L000016586",
                                "LPI_LANGUAGE": "ENG",
                                "LPI_LOGICAL_STATUS": 1,
                                "LPI_START_DATE": "9/15/1992 12:00:00 AM",
                                "LPI_END_DATE": null,
                                "LPI_LAST_UPDATE_DATE": "9/29/2011 12:00:00 AM",
                                "LPI_ENTRY_DATE": "9/15/1992 12:00:00 AM",
                                "SAO_START_NUMBER": "",
                                "SAO_END_NUMBER": "",
                                "SAO_START_SUFFIX": "",
                                "SAO_END_SUFFIX": "",
                                "SAO_TEXT": "",
                                "PAO_START_NUMBER": "111",
                                "PAO_END_NUMBER": "",
                                "PAO_START_SUFFIX": "",
                                "PAO_END_SUFFIX": "",
                                "PAO_TEXT": "",
                                "LEVEL": "",
                                "POSTALLY_ADDRESSABLE": "Y",
                                "POSTCODE": "EH8 8AS",
                                "POST_TOWN": "EDINBURGH",
                                "OFFICIAL_FLAG": "Y",
                                "LPI_CUSTODIAN_ONE": null,
                                "LPI_CUSTODIAN_TWO": null,
                                "STREET_RECORD_TYPE": 1,
                                "SWA_ORG_REF_NAMING": 9064,
                                "STREET_STATE": null,
                                "STREET_STATE_DATE": "11/27/1995 12:00:00 AM",
                                "STREET_SURFACE": 1,
                                "STREET_CLASSIFICATION": 8,
                                "STREET_VERSION": 0,
                                "STREET_LAST_UPDATE_DATE": "1/28/2009 12:00:00 AM",
                                "STREET_START_DATE": null,
                                "STREET_END_DATE": null,
                                "STREET_TOLERANCE": 1,
                                "STREET_START_X": 326711,
                                "STREET_START_Y": 673773,
                                "STREET_END_X": 326208,
                                "STREET_END_Y": 673543,
                                "STREET_DESCRIPTOR": "HOLYROOD ROAD",
                                "LOCALITY_NAME": "",
                                "ADMINISTRATIVE_AREA": "CITY OF EDINBURGH",
                                "TOWN_NAME": "EDINBURGH",
                                "STREET_LANGUAGE": "ENG",
                                "USRN": "7901866"
                            },
                            "SortDescription": ""
                        }
                    ],
                    "Level": 1,
                    "SortDescription": "111"
                }
            ],
            "Level": 0,
            "SortDescription": ""
        }
    ]
};


var agsLLPGResults = {
    "spatialReference": {
        "wkid": 27700,
        "latestWkid": 27700
    },
    "candidates": [
     {
         "address": "FLAT 1, 205, PORTOBELLO HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH15 1EU",
         "location": {
             "x": 330582.00039980002,
             "y": 673808.00036345003
         },
         "score": 100,
         "attributes": {
             "Score": 100,
             "Match_addr": "FLAT 1, 205, PORTOBELLO HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH15 1EU",
             "X": 330582.00040000002,
             "Y": 673808.00036299997,
             "UPRN": "906201311",
             "USRN": "7902439",
             "BLPULogicalStatus": 1,
             "RPC": 1,
             "PostalAddress": "Y",
             "Organisation": "",
             "LPIKey": "9064L000115259",
             "LPILogicalStatus": 1,
             "SAOStartNumber": 0,
             "SAOEndNumber": 0,
             "SAOStartSuffix": "",
             "SAOEndSuffix": "",
             "SAONumberRange": "",
             "SAOText": "FLAT 1",
             "PAOStartNumber": 205,
             "PAOEndNumber": 0,
             "PAOStartSuffix": "",
             "PAOEndSuffix": "",
             "PAONumberRange": "205",
             "PAOText": "",
             "StreetDescriptor": "PORTOBELLO HIGH STREET",
             "LocalityName": "",
             "Town": "EDINBURGH",
             "AdminArea": "CITY OF EDINBURGH",
             "Postcode": "EH15 1EU",
             "Language": "English",
             "Currency": "Current",
             "Addr_type": "Address"
         }
     },
     {
         "address": "FLAT 2, 205, PORTOBELLO HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH15 1EU",
         "location": {
             "x": 330582.00039980002,
             "y": 673808.00036345003
         },
         "score": 100,
         "attributes": {
             "Score": 100,
             "Match_addr": "FLAT 2, 205, PORTOBELLO HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH15 1EU",
             "X": 330582.00040000002,
             "Y": 673808.00036299997,
             "UPRN": "906201312",
             "USRN": "7902439",
             "BLPULogicalStatus": 1,
             "RPC": 1,
             "PostalAddress": "Y",
             "Organisation": "",
             "LPIKey": "9064L000115260",
             "LPILogicalStatus": 1,
             "SAOStartNumber": 0,
             "SAOEndNumber": 0,
             "SAOStartSuffix": "",
             "SAOEndSuffix": "",
             "SAONumberRange": "",
             "SAOText": "FLAT 2",
             "PAOStartNumber": 205,
             "PAOEndNumber": 0,
             "PAOStartSuffix": "",
             "PAOEndSuffix": "",
             "PAONumberRange": "205",
             "PAOText": "",
             "StreetDescriptor": "PORTOBELLO HIGH STREET",
             "LocalityName": "",
             "Town": "EDINBURGH",
             "AdminArea": "CITY OF EDINBURGH",
             "Postcode": "EH15 1EU",
             "Language": "English",
             "Currency": "Current",
             "Addr_type": "Address"
         }
     },
     {
         "address": "FLAT 3, 205, PORTOBELLO HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH15 1EU",
         "location": {
             "x": 330582.00039980002,
             "y": 673808.00036345003
         },
         "score": 100,
         "attributes": {
             "Score": 100,
             "Match_addr": "FLAT 3, 205, PORTOBELLO HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH15 1EU",
             "X": 330582.00040000002,
             "Y": 673808.00036299997,
             "UPRN": "906201313",
             "USRN": "7902439",
             "BLPULogicalStatus": 1,
             "RPC": 1,
             "PostalAddress": "Y",
             "Organisation": "",
             "LPIKey": "9064L000115261",
             "LPILogicalStatus": 1,
             "SAOStartNumber": 0,
             "SAOEndNumber": 0,
             "SAOStartSuffix": "",
             "SAOEndSuffix": "",
             "SAONumberRange": "",
             "SAOText": "FLAT 3",
             "PAOStartNumber": 205,
             "PAOEndNumber": 0,
             "PAOStartSuffix": "",
             "PAOEndSuffix": "",
             "PAONumberRange": "205",
             "PAOText": "",
             "StreetDescriptor": "PORTOBELLO HIGH STREET",
             "LocalityName": "",
             "Town": "EDINBURGH",
             "AdminArea": "CITY OF EDINBURGH",
             "Postcode": "EH15 1EU",
             "Language": "English",
             "Currency": "Current",
             "Addr_type": "Address"
         }
     }
    ]
};

var singleAGSLLPGResults = {
    "spatialReference": {
        "wkid": 27700,
        "latestWkid": 27700
    },
    "candidates": [
     {
         "address": "FLAT 3, 205, PORTOBELLO HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH15 1EU",
         "location": {
             "x": 330582.00039980002,
             "y": 673808.00036345003
         },
         "score": 100,
         "attributes": {
             "Score": 100,
             "Match_addr": "FLAT 3, 205, PORTOBELLO HIGH STREET, EDINBURGH, CITY OF EDINBURGH, EH15 1EU",
             "X": 330582.00040000002,
             "Y": 673808.00036299997,
             "UPRN": "906201313",
             "USRN": "7902439",
             "BLPULogicalStatus": 1,
             "RPC": 1,
             "PostalAddress": "Y",
             "Organisation": "",
             "LPIKey": "9064L000115261",
             "LPILogicalStatus": 1,
             "SAOStartNumber": 0,
             "SAOEndNumber": 0,
             "SAOStartSuffix": "",
             "SAOEndSuffix": "",
             "SAONumberRange": "",
             "SAOText": "FLAT 3",
             "PAOStartNumber": 205,
             "PAOEndNumber": 0,
             "PAOStartSuffix": "",
             "PAOEndSuffix": "",
             "PAONumberRange": "205",
             "PAOText": "",
             "StreetDescriptor": "PORTOBELLO HIGH STREET",
             "LocalityName": "",
             "Town": "EDINBURGH",
             "AdminArea": "CITY OF EDINBURGH",
             "Postcode": "EH15 1EU",
             "Language": "English",
             "Currency": "Current",
             "Addr_type": "Address"
         }
     }
    ]
};
