var llpgResults = {
    "spatialReference": {
        "wkid": 27700,
        "latestWkid": 27700
    },
    "candidates": [
        {
            "address": "CONFERENCE CENTRE, 35 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AA",
            "location": {
                "x": 528352,
                "y": 181795
            },
            "score": 100,
            "attributes": {
                "Match_addr": "CONFERENCE CENTRE, 35 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AA",
                "Addr_type": "Address",
                "LOCATOR_ENVELOPE": "528352,181795,528352,181795",
                "LOCATOR_POINT": "528352,181795",
                "LOCATOR_DESCRIPTION": "CONFERENCE CENTRE, 35 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AA",
                "LOCATOR_FAMILY_ID": "10033572222",
                "LOCATOR_ID": "21770",
                "LOCATOR_DATASET_ID": "5990L000144686:ENG",
                "LOCATOR_DATASET_FAMILY_ID": "10033572222",
                "LOCATOR_RESOLUTION": 90,
                "LOCATOR_SCORE": 100,
                "UPRN": "10033572222",
                "BLPU_LOGICAL_STATUS": 1,
                "BLPU_STATE": 2,
                "BLPU_STATE_DATE": "29/12/2005 00:00:00",
                "PARENT_UPRN": "",
                "RPA": 1,
                "LOCAL_CUSTODIAN_CODE": 5990,
                "BLPU_START_DATE": "29/12/2005 00:00:00",
                "BLPU_END_DATE": null,
                "BLPU_LAST_UPDATE_DATE": "29/12/2005 00:00:00",
                "BLPU_ENTRY_DATE": "29/12/2005 00:00:00",
                "ORGANISATION": "",
                "BLPU_CLASS": "U",
                "WARD_CODE": "",
                "PARISH_CODE": "",
                "BLPU_CUSTODIAN_ONE": null,
                "BLPU_CUSTODIAN_TWO": null,
                "LPI_KEY": "5990L000144686",
                "LPI_LANGUAGE": "ENG",
                "LPI_LOGICAL_STATUS": 1,
                "LPI_START_DATE": "29/12/2005 00:00:00",
                "LPI_END_DATE": null,
                "LPI_LAST_UPDATE_DATE": "29/12/2005 00:00:00",
                "LPI_ENTRY_DATE": "29/12/2005 00:00:00",
                "SAO_START_NUMBER": "",
                "SAO_END_NUMBER": "",
                "SAO_START_SUFFIX": "",
                "SAO_END_SUFFIX": "",
                "SAO_TEXT": "",
                "PAO_START_NUMBER": "35",
                "PAO_END_NUMBER": "",
                "PAO_START_SUFFIX": "",
                "PAO_END_SUFFIX": "",
                "PAO_TEXT": "CONFERENCE CENTRE",
                "LEVEL": "",
                "POSTALLY_ADDRESSABLE": "Y",
                "POSTCODE": "W1U 4AA",
                "POST_TOWN": "LONDON",
                "OFFICIAL_FLAG": "Y",
                "LPI_CUSTODIAN_ONE": null,
                "LPI_CUSTODIAN_TWO": null,
                "STREET_RECORD_TYPE": 1,
                "SWA_ORG_REF_NAMING": 5990,
                "STREET_STATE": null,
                "STREET_STATE_DATE": null,
                "STREET_SURFACE": null,
                "STREET_CLASSIFICATION": null,
                "STREET_VERSION": 0,
                "STREET_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "STREET_START_DATE": null,
                "STREET_END_DATE": null,
                "STREET_TOLERANCE": 1,
                "STREET_START_X": 528350,
                "STREET_START_Y": 181538,
                "STREET_END_X": 528365,
                "STREET_END_Y": 182083,
                "STREET_DESCRIPTOR": "MARYLEBONE HIGH STREET",
                "LOCALITY_NAME": "",
                "ADMINISTRATIVE_AREA": "CITY OF WESTMINSTER",
                "TOWN_NAME": "LONDON",
                "STREET_LANGUAGE": "ENG",
                "USRN": "8401405"
            }
        },
        {
            "address": "27 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AD",
            "location": {
                "x": 528343,
                "y": 181722
            },
            "score": 100,
            "attributes": {
                "Match_addr": "27 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AD",
                "Addr_type": "Address",
                "LOCATOR_ENVELOPE": "528343,181722,528343,181722",
                "LOCATOR_POINT": "528343,181722",
                "LOCATOR_DESCRIPTION": "27 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AD",
                "LOCATOR_FAMILY_ID": "100023464227",
                "LOCATOR_ID": "41342",
                "LOCATOR_DATASET_ID": "5990L000117569:ENG",
                "LOCATOR_DATASET_FAMILY_ID": "100023464227",
                "LOCATOR_RESOLUTION": 90,
                "LOCATOR_SCORE": 100,
                "UPRN": "100023464227",
                "BLPU_LOGICAL_STATUS": 1,
                "BLPU_STATE": 2,
                "BLPU_STATE_DATE": "19/03/2001 00:00:00",
                "PARENT_UPRN": "",
                "RPA": 1,
                "LOCAL_CUSTODIAN_CODE": 5990,
                "BLPU_START_DATE": "19/03/2001 00:00:00",
                "BLPU_END_DATE": null,
                "BLPU_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "BLPU_ENTRY_DATE": "26/03/2001 00:00:00",
                "ORGANISATION": "",
                "BLPU_CLASS": "U",
                "WARD_CODE": "",
                "PARISH_CODE": "",
                "BLPU_CUSTODIAN_ONE": null,
                "BLPU_CUSTODIAN_TWO": null,
                "LPI_KEY": "5990L000117569",
                "LPI_LANGUAGE": "ENG",
                "LPI_LOGICAL_STATUS": 1,
                "LPI_START_DATE": "19/03/2001 00:00:00",
                "LPI_END_DATE": null,
                "LPI_LAST_UPDATE_DATE": "28/11/2006 00:00:00",
                "LPI_ENTRY_DATE": "26/03/2001 00:00:00",
                "SAO_START_NUMBER": "",
                "SAO_END_NUMBER": "",
                "SAO_START_SUFFIX": "",
                "SAO_END_SUFFIX": "",
                "SAO_TEXT": "",
                "PAO_START_NUMBER": "27",
                "PAO_END_NUMBER": "",
                "PAO_START_SUFFIX": "",
                "PAO_END_SUFFIX": "",
                "PAO_TEXT": "",
                "LEVEL": "",
                "POSTALLY_ADDRESSABLE": "Y",
                "POSTCODE": "W1U 4AD",
                "POST_TOWN": "LONDON",
                "OFFICIAL_FLAG": "",
                "LPI_CUSTODIAN_ONE": null,
                "LPI_CUSTODIAN_TWO": null,
                "STREET_RECORD_TYPE": 1,
                "SWA_ORG_REF_NAMING": 5990,
                "STREET_STATE": null,
                "STREET_STATE_DATE": null,
                "STREET_SURFACE": null,
                "STREET_CLASSIFICATION": null,
                "STREET_VERSION": 0,
                "STREET_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "STREET_START_DATE": null,
                "STREET_END_DATE": null,
                "STREET_TOLERANCE": 1,
                "STREET_START_X": 528350,
                "STREET_START_Y": 181538,
                "STREET_END_X": 528365,
                "STREET_END_Y": 182083,
                "STREET_DESCRIPTOR": "MARYLEBONE HIGH STREET",
                "LOCALITY_NAME": "",
                "ADMINISTRATIVE_AREA": "CITY OF WESTMINSTER",
                "TOWN_NAME": "LONDON",
                "STREET_LANGUAGE": "ENG",
                "USRN": "8401405"
            }
        },
        {
            "address": "BASEMENT AND GROUND FLOOR, 27 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AD",
            "location": {
                "x": 528343,
                "y": 181722
            },
            "score": 100,
            "attributes": {
                "Match_addr": "BASEMENT AND GROUND FLOOR, 27 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AD",
                "Addr_type": "Address",
                "LOCATOR_ENVELOPE": "528343,181722,528343,181722",
                "LOCATOR_POINT": "528343,181722",
                "LOCATOR_DESCRIPTION": "BASEMENT AND GROUND FLOOR, 27 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AD",
                "LOCATOR_FAMILY_ID": "10033583998",
                "LOCATOR_ID": "97791",
                "LOCATOR_DATASET_ID": "5990L000198692:ENG",
                "LOCATOR_DATASET_FAMILY_ID": "10033583998",
                "LOCATOR_RESOLUTION": 90,
                "LOCATOR_SCORE": 100,
                "UPRN": "10033583998",
                "BLPU_LOGICAL_STATUS": 1,
                "BLPU_STATE": 2,
                "BLPU_STATE_DATE": "10/08/2006 00:00:00",
                "PARENT_UPRN": "100023464227",
                "RPA": 1,
                "LOCAL_CUSTODIAN_CODE": 5990,
                "BLPU_START_DATE": "10/08/2006 00:00:00",
                "BLPU_END_DATE": null,
                "BLPU_LAST_UPDATE_DATE": "10/08/2006 00:00:00",
                "BLPU_ENTRY_DATE": "10/08/2006 00:00:00",
                "ORGANISATION": "",
                "BLPU_CLASS": "CR01",
                "WARD_CODE": "",
                "PARISH_CODE": "",
                "BLPU_CUSTODIAN_ONE": null,
                "BLPU_CUSTODIAN_TWO": null,
                "LPI_KEY": "5990L000198692",
                "LPI_LANGUAGE": "ENG",
                "LPI_LOGICAL_STATUS": 1,
                "LPI_START_DATE": "10/08/2006 00:00:00",
                "LPI_END_DATE": null,
                "LPI_LAST_UPDATE_DATE": "10/08/2006 00:00:00",
                "LPI_ENTRY_DATE": "10/08/2006 00:00:00",
                "SAO_START_NUMBER": "",
                "SAO_END_NUMBER": "",
                "SAO_START_SUFFIX": "",
                "SAO_END_SUFFIX": "",
                "SAO_TEXT": "BASEMENT AND GROUND FLOOR",
                "PAO_START_NUMBER": "27",
                "PAO_END_NUMBER": "",
                "PAO_START_SUFFIX": "",
                "PAO_END_SUFFIX": "",
                "PAO_TEXT": "",
                "LEVEL": "",
                "POSTALLY_ADDRESSABLE": "Y",
                "POSTCODE": "W1U 4AD",
                "POST_TOWN": "LONDON",
                "OFFICIAL_FLAG": "Y",
                "LPI_CUSTODIAN_ONE": null,
                "LPI_CUSTODIAN_TWO": null,
                "STREET_RECORD_TYPE": 1,
                "SWA_ORG_REF_NAMING": 5990,
                "STREET_STATE": null,
                "STREET_STATE_DATE": null,
                "STREET_SURFACE": null,
                "STREET_CLASSIFICATION": null,
                "STREET_VERSION": 0,
                "STREET_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "STREET_START_DATE": null,
                "STREET_END_DATE": null,
                "STREET_TOLERANCE": 1,
                "STREET_START_X": 528350,
                "STREET_START_Y": 181538,
                "STREET_END_X": 528365,
                "STREET_END_Y": 182083,
                "STREET_DESCRIPTOR": "MARYLEBONE HIGH STREET",
                "LOCALITY_NAME": "",
                "ADMINISTRATIVE_AREA": "CITY OF WESTMINSTER",
                "TOWN_NAME": "LONDON",
                "STREET_LANGUAGE": "ENG",
                "USRN": "8401405"
            }
        },
        {
            "address": "FIRST FLOOR, 10 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AF",
            "location": {
                "x": 528363,
                "y": 181624
            },
            "score": 100,
            "attributes": {
                "Match_addr": "FIRST FLOOR, 10 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AF",
                "Addr_type": "Address",
                "LOCATOR_ENVELOPE": "528363,181624,528363,181624",
                "LOCATOR_POINT": "528363,181624",
                "LOCATOR_DESCRIPTION": "FIRST FLOOR, 10 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AF",
                "LOCATOR_FAMILY_ID": "10033570428",
                "LOCATOR_ID": "79642",
                "LOCATOR_DATASET_ID": "5990L000140480:ENG",
                "LOCATOR_DATASET_FAMILY_ID": "10033570428",
                "LOCATOR_RESOLUTION": 90,
                "LOCATOR_SCORE": 100,
                "UPRN": "10033570428",
                "BLPU_LOGICAL_STATUS": 1,
                "BLPU_STATE": 2,
                "BLPU_STATE_DATE": "10/11/2005 00:00:00",
                "PARENT_UPRN": "100023464224",
                "RPA": 1,
                "LOCAL_CUSTODIAN_CODE": 5990,
                "BLPU_START_DATE": "10/11/2005 00:00:00",
                "BLPU_END_DATE": null,
                "BLPU_LAST_UPDATE_DATE": "10/11/2005 00:00:00",
                "BLPU_ENTRY_DATE": "10/11/2005 00:00:00",
                "ORGANISATION": "",
                "BLPU_CLASS": "U",
                "WARD_CODE": "",
                "PARISH_CODE": "",
                "BLPU_CUSTODIAN_ONE": null,
                "BLPU_CUSTODIAN_TWO": null,
                "LPI_KEY": "5990L000140480",
                "LPI_LANGUAGE": "ENG",
                "LPI_LOGICAL_STATUS": 1,
                "LPI_START_DATE": "10/11/2005 00:00:00",
                "LPI_END_DATE": null,
                "LPI_LAST_UPDATE_DATE": "10/11/2005 00:00:00",
                "LPI_ENTRY_DATE": "10/11/2005 00:00:00",
                "SAO_START_NUMBER": "",
                "SAO_END_NUMBER": "",
                "SAO_START_SUFFIX": "",
                "SAO_END_SUFFIX": "",
                "SAO_TEXT": "FIRST FLOOR",
                "PAO_START_NUMBER": "10",
                "PAO_END_NUMBER": "",
                "PAO_START_SUFFIX": "",
                "PAO_END_SUFFIX": "",
                "PAO_TEXT": "",
                "LEVEL": "",
                "POSTALLY_ADDRESSABLE": "Y",
                "POSTCODE": "W1U 4AF",
                "POST_TOWN": "LONDON",
                "OFFICIAL_FLAG": "Y",
                "LPI_CUSTODIAN_ONE": null,
                "LPI_CUSTODIAN_TWO": null,
                "STREET_RECORD_TYPE": 1,
                "SWA_ORG_REF_NAMING": 5990,
                "STREET_STATE": null,
                "STREET_STATE_DATE": null,
                "STREET_SURFACE": null,
                "STREET_CLASSIFICATION": null,
                "STREET_VERSION": 0,
                "STREET_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "STREET_START_DATE": null,
                "STREET_END_DATE": null,
                "STREET_TOLERANCE": 1,
                "STREET_START_X": 528350,
                "STREET_START_Y": 181538,
                "STREET_END_X": 528365,
                "STREET_END_Y": 182083,
                "STREET_DESCRIPTOR": "MARYLEBONE HIGH STREET",
                "LOCALITY_NAME": "",
                "ADMINISTRATIVE_AREA": "CITY OF WESTMINSTER",
                "TOWN_NAME": "LONDON",
                "STREET_LANGUAGE": "ENG",
                "USRN": "8401405"
            }
        },
        {
            "address": "10 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AF",
            "location": {
                "x": 528363,
                "y": 181624
            },
            "score": 100,
            "attributes": {
                "Match_addr": "10 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AF",
                "Addr_type": "Address",
                "LOCATOR_ENVELOPE": "528363,181624,528363,181624",
                "LOCATOR_POINT": "528363,181624",
                "LOCATOR_DESCRIPTION": "10 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AF",
                "LOCATOR_FAMILY_ID": "100023464224",
                "LOCATOR_ID": "38363",
                "LOCATOR_DATASET_ID": "5990L000117567:ENG",
                "LOCATOR_DATASET_FAMILY_ID": "100023464224",
                "LOCATOR_RESOLUTION": 90,
                "LOCATOR_SCORE": 100,
                "UPRN": "100023464224",
                "BLPU_LOGICAL_STATUS": 1,
                "BLPU_STATE": 2,
                "BLPU_STATE_DATE": "19/03/2001 00:00:00",
                "PARENT_UPRN": "",
                "RPA": 1,
                "LOCAL_CUSTODIAN_CODE": 5990,
                "BLPU_START_DATE": "19/03/2001 00:00:00",
                "BLPU_END_DATE": null,
                "BLPU_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "BLPU_ENTRY_DATE": "26/03/2001 00:00:00",
                "ORGANISATION": "",
                "BLPU_CLASS": "PP",
                "WARD_CODE": "",
                "PARISH_CODE": "",
                "BLPU_CUSTODIAN_ONE": null,
                "BLPU_CUSTODIAN_TWO": null,
                "LPI_KEY": "5990L000117567",
                "LPI_LANGUAGE": "ENG",
                "LPI_LOGICAL_STATUS": 1,
                "LPI_START_DATE": "19/03/2001 00:00:00",
                "LPI_END_DATE": null,
                "LPI_LAST_UPDATE_DATE": "14/12/2007 00:00:00",
                "LPI_ENTRY_DATE": "26/03/2001 00:00:00",
                "SAO_START_NUMBER": "",
                "SAO_END_NUMBER": "",
                "SAO_START_SUFFIX": "",
                "SAO_END_SUFFIX": "",
                "SAO_TEXT": "",
                "PAO_START_NUMBER": "10",
                "PAO_END_NUMBER": "",
                "PAO_START_SUFFIX": "",
                "PAO_END_SUFFIX": "",
                "PAO_TEXT": "",
                "LEVEL": "",
                "POSTALLY_ADDRESSABLE": "N",
                "POSTCODE": "W1U 4AF",
                "POST_TOWN": "",
                "OFFICIAL_FLAG": "",
                "LPI_CUSTODIAN_ONE": null,
                "LPI_CUSTODIAN_TWO": null,
                "STREET_RECORD_TYPE": 1,
                "SWA_ORG_REF_NAMING": 5990,
                "STREET_STATE": null,
                "STREET_STATE_DATE": null,
                "STREET_SURFACE": null,
                "STREET_CLASSIFICATION": null,
                "STREET_VERSION": 0,
                "STREET_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "STREET_START_DATE": null,
                "STREET_END_DATE": null,
                "STREET_TOLERANCE": 1,
                "STREET_START_X": 528350,
                "STREET_START_Y": 181538,
                "STREET_END_X": 528365,
                "STREET_END_Y": 182083,
                "STREET_DESCRIPTOR": "MARYLEBONE HIGH STREET",
                "LOCALITY_NAME": "",
                "ADMINISTRATIVE_AREA": "CITY OF WESTMINSTER",
                "TOWN_NAME": "LONDON",
                "STREET_LANGUAGE": "ENG",
                "USRN": "8401405"
            }
        },
        {
            "address": "19 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BD",
            "location": {
                "x": 528356,
                "y": 181675
            },
            "score": 100,
            "attributes": {
                "Match_addr": "19 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BD",
                "Addr_type": "Address",
                "LOCATOR_ENVELOPE": "528356,181675,528356,181675",
                "LOCATOR_POINT": "528356,181675",
                "LOCATOR_DESCRIPTION": "19 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BD",
                "LOCATOR_FAMILY_ID": "100023464228",
                "LOCATOR_ID": "40311",
                "LOCATOR_DATASET_ID": "5990L000117570:ENG",
                "LOCATOR_DATASET_FAMILY_ID": "100023464228",
                "LOCATOR_RESOLUTION": 90,
                "LOCATOR_SCORE": 100,
                "UPRN": "100023464228",
                "BLPU_LOGICAL_STATUS": 1,
                "BLPU_STATE": 2,
                "BLPU_STATE_DATE": "19/03/2001 00:00:00",
                "PARENT_UPRN": "",
                "RPA": 1,
                "LOCAL_CUSTODIAN_CODE": 5990,
                "BLPU_START_DATE": "19/03/2001 00:00:00",
                "BLPU_END_DATE": null,
                "BLPU_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "BLPU_ENTRY_DATE": "26/03/2001 00:00:00",
                "ORGANISATION": "",
                "BLPU_CLASS": "U",
                "WARD_CODE": "",
                "PARISH_CODE": "",
                "BLPU_CUSTODIAN_ONE": null,
                "BLPU_CUSTODIAN_TWO": null,
                "LPI_KEY": "5990L000117570",
                "LPI_LANGUAGE": "ENG",
                "LPI_LOGICAL_STATUS": 1,
                "LPI_START_DATE": "19/03/2001 00:00:00",
                "LPI_END_DATE": null,
                "LPI_LAST_UPDATE_DATE": "14/12/2007 00:00:00",
                "LPI_ENTRY_DATE": "26/03/2001 00:00:00",
                "SAO_START_NUMBER": "",
                "SAO_END_NUMBER": "",
                "SAO_START_SUFFIX": "",
                "SAO_END_SUFFIX": "",
                "SAO_TEXT": "",
                "PAO_START_NUMBER": "19",
                "PAO_END_NUMBER": "",
                "PAO_START_SUFFIX": "",
                "PAO_END_SUFFIX": "",
                "PAO_TEXT": "",
                "LEVEL": "",
                "POSTALLY_ADDRESSABLE": "Y",
                "POSTCODE": "W1U 4BD",
                "POST_TOWN": "LONDON",
                "OFFICIAL_FLAG": "",
                "LPI_CUSTODIAN_ONE": null,
                "LPI_CUSTODIAN_TWO": null,
                "STREET_RECORD_TYPE": 1,
                "SWA_ORG_REF_NAMING": 5990,
                "STREET_STATE": null,
                "STREET_STATE_DATE": null,
                "STREET_SURFACE": null,
                "STREET_CLASSIFICATION": null,
                "STREET_VERSION": 0,
                "STREET_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "STREET_START_DATE": null,
                "STREET_END_DATE": null,
                "STREET_TOLERANCE": 1,
                "STREET_START_X": 528350,
                "STREET_START_Y": 181538,
                "STREET_END_X": 528365,
                "STREET_END_Y": 182083,
                "STREET_DESCRIPTOR": "MARYLEBONE HIGH STREET",
                "LOCALITY_NAME": "",
                "ADMINISTRATIVE_AREA": "CITY OF WESTMINSTER",
                "TOWN_NAME": "LONDON",
                "STREET_LANGUAGE": "ENG",
                "USRN": "8401405"
            }
        },
        {
            "address": "18-19 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BD",
            "location": {
                "x": 528356,
                "y": 181675
            },
            "score": 100,
            "attributes": {
                "Match_addr": "18-19 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BD",
                "Addr_type": "Address",
                "LOCATOR_ENVELOPE": "528356,181675,528356,181675",
                "LOCATOR_POINT": "528356,181675",
                "LOCATOR_DESCRIPTION": "18-19 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BD",
                "LOCATOR_FAMILY_ID": "10033583118",
                "LOCATOR_ID": "10794",
                "LOCATOR_DATASET_ID": "5990L000155816:ENG",
                "LOCATOR_DATASET_FAMILY_ID": "10033583118",
                "LOCATOR_RESOLUTION": 90,
                "LOCATOR_SCORE": 100,
                "UPRN": "10033583118",
                "BLPU_LOGICAL_STATUS": 1,
                "BLPU_STATE": 2,
                "BLPU_STATE_DATE": "25/07/2006 00:00:00",
                "PARENT_UPRN": "",
                "RPA": 1,
                "LOCAL_CUSTODIAN_CODE": 5990,
                "BLPU_START_DATE": "25/07/2006 00:00:00",
                "BLPU_END_DATE": null,
                "BLPU_LAST_UPDATE_DATE": "25/07/2006 00:00:00",
                "BLPU_ENTRY_DATE": "25/07/2006 00:00:00",
                "ORGANISATION": "",
                "BLPU_CLASS": "PP",
                "WARD_CODE": "",
                "PARISH_CODE": "",
                "BLPU_CUSTODIAN_ONE": null,
                "BLPU_CUSTODIAN_TWO": null,
                "LPI_KEY": "5990L000155816",
                "LPI_LANGUAGE": "ENG",
                "LPI_LOGICAL_STATUS": 1,
                "LPI_START_DATE": "25/07/2006 00:00:00",
                "LPI_END_DATE": null,
                "LPI_LAST_UPDATE_DATE": "25/07/2006 00:00:00",
                "LPI_ENTRY_DATE": "25/07/2006 00:00:00",
                "SAO_START_NUMBER": "",
                "SAO_END_NUMBER": "",
                "SAO_START_SUFFIX": "",
                "SAO_END_SUFFIX": "",
                "SAO_TEXT": "",
                "PAO_START_NUMBER": "18",
                "PAO_END_NUMBER": "19",
                "PAO_START_SUFFIX": "",
                "PAO_END_SUFFIX": "",
                "PAO_TEXT": "",
                "LEVEL": "",
                "POSTALLY_ADDRESSABLE": "Y",
                "POSTCODE": "W1U 4BD",
                "POST_TOWN": "LONDON",
                "OFFICIAL_FLAG": "Y",
                "LPI_CUSTODIAN_ONE": null,
                "LPI_CUSTODIAN_TWO": null,
                "STREET_RECORD_TYPE": 1,
                "SWA_ORG_REF_NAMING": 5990,
                "STREET_STATE": null,
                "STREET_STATE_DATE": null,
                "STREET_SURFACE": null,
                "STREET_CLASSIFICATION": null,
                "STREET_VERSION": 0,
                "STREET_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "STREET_START_DATE": null,
                "STREET_END_DATE": null,
                "STREET_TOLERANCE": 1,
                "STREET_START_X": 528350,
                "STREET_START_Y": 181538,
                "STREET_END_X": 528365,
                "STREET_END_Y": 182083,
                "STREET_DESCRIPTOR": "MARYLEBONE HIGH STREET",
                "LOCALITY_NAME": "",
                "ADMINISTRATIVE_AREA": "CITY OF WESTMINSTER",
                "TOWN_NAME": "LONDON",
                "STREET_LANGUAGE": "ENG",
                "USRN": "8401405"
            }
        },
        {
            "address": "BASEMENT AND GROUND FLOOR, 18-19 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BD",
            "location": {
                "x": 528356,
                "y": 181675
            },
            "score": 100,
            "attributes": {
                "Match_addr": "BASEMENT AND GROUND FLOOR, 18-19 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BD",
                "Addr_type": "Address",
                "LOCATOR_ENVELOPE": "528356,181675,528356,181675",
                "LOCATOR_POINT": "528356,181675",
                "LOCATOR_DESCRIPTION": "BASEMENT AND GROUND FLOOR, 18-19 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BD",
                "LOCATOR_FAMILY_ID": "10033587641",
                "LOCATOR_ID": "94038",
                "LOCATOR_DATASET_ID": "5990L000182012:ENG",
                "LOCATOR_DATASET_FAMILY_ID": "10033587641",
                "LOCATOR_RESOLUTION": 90,
                "LOCATOR_SCORE": 100,
                "UPRN": "10033587641",
                "BLPU_LOGICAL_STATUS": 1,
                "BLPU_STATE": 2,
                "BLPU_STATE_DATE": "21/08/2006 00:00:00",
                "PARENT_UPRN": "10033583118",
                "RPA": 1,
                "LOCAL_CUSTODIAN_CODE": 5990,
                "BLPU_START_DATE": "21/08/2006 00:00:00",
                "BLPU_END_DATE": null,
                "BLPU_LAST_UPDATE_DATE": "21/08/2006 00:00:00",
                "BLPU_ENTRY_DATE": "21/08/2006 00:00:00",
                "ORGANISATION": "",
                "BLPU_CLASS": "CR01",
                "WARD_CODE": "",
                "PARISH_CODE": "",
                "BLPU_CUSTODIAN_ONE": null,
                "BLPU_CUSTODIAN_TWO": null,
                "LPI_KEY": "5990L000182012",
                "LPI_LANGUAGE": "ENG",
                "LPI_LOGICAL_STATUS": 1,
                "LPI_START_DATE": "21/08/2006 00:00:00",
                "LPI_END_DATE": null,
                "LPI_LAST_UPDATE_DATE": "21/08/2006 00:00:00",
                "LPI_ENTRY_DATE": "21/08/2006 00:00:00",
                "SAO_START_NUMBER": "",
                "SAO_END_NUMBER": "",
                "SAO_START_SUFFIX": "",
                "SAO_END_SUFFIX": "",
                "SAO_TEXT": "BASEMENT AND GROUND FLOOR",
                "PAO_START_NUMBER": "18",
                "PAO_END_NUMBER": "19",
                "PAO_START_SUFFIX": "",
                "PAO_END_SUFFIX": "",
                "PAO_TEXT": "",
                "LEVEL": "",
                "POSTALLY_ADDRESSABLE": "Y",
                "POSTCODE": "W1U 4BD",
                "POST_TOWN": "LONDON",
                "OFFICIAL_FLAG": "Y",
                "LPI_CUSTODIAN_ONE": null,
                "LPI_CUSTODIAN_TWO": null,
                "STREET_RECORD_TYPE": 1,
                "SWA_ORG_REF_NAMING": 5990,
                "STREET_STATE": null,
                "STREET_STATE_DATE": null,
                "STREET_SURFACE": null,
                "STREET_CLASSIFICATION": null,
                "STREET_VERSION": 0,
                "STREET_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "STREET_START_DATE": null,
                "STREET_END_DATE": null,
                "STREET_TOLERANCE": 1,
                "STREET_START_X": 528350,
                "STREET_START_Y": 181538,
                "STREET_END_X": 528365,
                "STREET_END_Y": 182083,
                "STREET_DESCRIPTOR": "MARYLEBONE HIGH STREET",
                "LOCALITY_NAME": "",
                "ADMINISTRATIVE_AREA": "CITY OF WESTMINSTER",
                "TOWN_NAME": "LONDON",
                "STREET_LANGUAGE": "ENG",
                "USRN": "8401405"
            }
        },
        {
            "address": "GROUND FLOOR, 10 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BT",
            "location": {
                "x": 528363,
                "y": 181624
            },
            "score": 100,
            "attributes": {
                "Match_addr": "GROUND FLOOR, 10 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BT",
                "Addr_type": "Address",
                "LOCATOR_ENVELOPE": "528363,181624,528363,181624",
                "LOCATOR_POINT": "528363,181624",
                "LOCATOR_DESCRIPTION": "GROUND FLOOR, 10 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4BT",
                "LOCATOR_FAMILY_ID": "10033570427",
                "LOCATOR_ID": "80271",
                "LOCATOR_DATASET_ID": "5990L000140479:ENG",
                "LOCATOR_DATASET_FAMILY_ID": "10033570427",
                "LOCATOR_RESOLUTION": 90,
                "LOCATOR_SCORE": 100,
                "UPRN": "10033570427",
                "BLPU_LOGICAL_STATUS": 1,
                "BLPU_STATE": 2,
                "BLPU_STATE_DATE": "10/11/2005 00:00:00",
                "PARENT_UPRN": "100023464224",
                "RPA": 1,
                "LOCAL_CUSTODIAN_CODE": 5990,
                "BLPU_START_DATE": "10/11/2005 00:00:00",
                "BLPU_END_DATE": null,
                "BLPU_LAST_UPDATE_DATE": "10/11/2005 00:00:00",
                "BLPU_ENTRY_DATE": "10/11/2005 00:00:00",
                "ORGANISATION": "",
                "BLPU_CLASS": "CR01",
                "WARD_CODE": "",
                "PARISH_CODE": "",
                "BLPU_CUSTODIAN_ONE": null,
                "BLPU_CUSTODIAN_TWO": null,
                "LPI_KEY": "5990L000140479",
                "LPI_LANGUAGE": "ENG",
                "LPI_LOGICAL_STATUS": 1,
                "LPI_START_DATE": "10/11/2005 00:00:00",
                "LPI_END_DATE": null,
                "LPI_LAST_UPDATE_DATE": "10/11/2005 00:00:00",
                "LPI_ENTRY_DATE": "10/11/2005 00:00:00",
                "SAO_START_NUMBER": "",
                "SAO_END_NUMBER": "",
                "SAO_START_SUFFIX": "",
                "SAO_END_SUFFIX": "",
                "SAO_TEXT": "GROUND FLOOR",
                "PAO_START_NUMBER": "10",
                "PAO_END_NUMBER": "",
                "PAO_START_SUFFIX": "",
                "PAO_END_SUFFIX": "",
                "PAO_TEXT": "",
                "LEVEL": "",
                "POSTALLY_ADDRESSABLE": "Y",
                "POSTCODE": "W1U 4BT",
                "POST_TOWN": "LONDON",
                "OFFICIAL_FLAG": "Y",
                "LPI_CUSTODIAN_ONE": null,
                "LPI_CUSTODIAN_TWO": null,
                "STREET_RECORD_TYPE": 1,
                "SWA_ORG_REF_NAMING": 5990,
                "STREET_STATE": null,
                "STREET_STATE_DATE": null,
                "STREET_SURFACE": null,
                "STREET_CLASSIFICATION": null,
                "STREET_VERSION": 0,
                "STREET_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "STREET_START_DATE": null,
                "STREET_END_DATE": null,
                "STREET_TOLERANCE": 1,
                "STREET_START_X": 528350,
                "STREET_START_Y": 181538,
                "STREET_END_X": 528365,
                "STREET_END_Y": 182083,
                "STREET_DESCRIPTOR": "MARYLEBONE HIGH STREET",
                "LOCALITY_NAME": "",
                "ADMINISTRATIVE_AREA": "CITY OF WESTMINSTER",
                "TOWN_NAME": "LONDON",
                "STREET_LANGUAGE": "ENG",
                "USRN": "8401405"
            }
        },
        {
            "address": "1 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4DL",
            "location": {
                "x": 528366,
                "y": 181545
            },
            "score": 100,
            "attributes": {
                "Match_addr": "1 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4DL",
                "Addr_type": "Address",
                "LOCATOR_ENVELOPE": "528366,181545,528366,181545",
                "LOCATOR_POINT": "528366,181545",
                "LOCATOR_DESCRIPTION": "1 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4DL",
                "LOCATOR_FAMILY_ID": "100023464225",
                "LOCATOR_ID": "36200",
                "LOCATOR_DATASET_ID": "5990L000117568:ENG",
                "LOCATOR_DATASET_FAMILY_ID": "100023464225",
                "LOCATOR_RESOLUTION": 90,
                "LOCATOR_SCORE": 100,
                "UPRN": "100023464225",
                "BLPU_LOGICAL_STATUS": 1,
                "BLPU_STATE": 2,
                "BLPU_STATE_DATE": "19/03/2001 00:00:00",
                "PARENT_UPRN": "",
                "RPA": 1,
                "LOCAL_CUSTODIAN_CODE": 5990,
                "BLPU_START_DATE": "19/03/2001 00:00:00",
                "BLPU_END_DATE": null,
                "BLPU_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "BLPU_ENTRY_DATE": "26/03/2001 00:00:00",
                "ORGANISATION": "",
                "BLPU_CLASS": "U",
                "WARD_CODE": "",
                "PARISH_CODE": "",
                "BLPU_CUSTODIAN_ONE": null,
                "BLPU_CUSTODIAN_TWO": null,
                "LPI_KEY": "5990L000117568",
                "LPI_LANGUAGE": "ENG",
                "LPI_LOGICAL_STATUS": 1,
                "LPI_START_DATE": "19/03/2001 00:00:00",
                "LPI_END_DATE": null,
                "LPI_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "LPI_ENTRY_DATE": "26/03/2001 00:00:00",
                "SAO_START_NUMBER": "",
                "SAO_END_NUMBER": "",
                "SAO_START_SUFFIX": "",
                "SAO_END_SUFFIX": "",
                "SAO_TEXT": "",
                "PAO_START_NUMBER": "1",
                "PAO_END_NUMBER": "",
                "PAO_START_SUFFIX": "",
                "PAO_END_SUFFIX": "",
                "PAO_TEXT": "",
                "LEVEL": "",
                "POSTALLY_ADDRESSABLE": "Y",
                "POSTCODE": "W1U 4DL",
                "POST_TOWN": "LONDON",
                "OFFICIAL_FLAG": "",
                "LPI_CUSTODIAN_ONE": null,
                "LPI_CUSTODIAN_TWO": null,
                "STREET_RECORD_TYPE": 1,
                "SWA_ORG_REF_NAMING": 5990,
                "STREET_STATE": null,
                "STREET_STATE_DATE": null,
                "STREET_SURFACE": null,
                "STREET_CLASSIFICATION": null,
                "STREET_VERSION": 0,
                "STREET_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "STREET_START_DATE": null,
                "STREET_END_DATE": null,
                "STREET_TOLERANCE": 1,
                "STREET_START_X": 528350,
                "STREET_START_Y": 181538,
                "STREET_END_X": 528365,
                "STREET_END_Y": 182083,
                "STREET_DESCRIPTOR": "MARYLEBONE HIGH STREET",
                "LOCALITY_NAME": "",
                "ADMINISTRATIVE_AREA": "CITY OF WESTMINSTER",
                "TOWN_NAME": "LONDON",
                "STREET_LANGUAGE": "ENG",
                "USRN": "8401405"
            }
        }
    ]
};

var singleLlpgResult = {
    "spatialReference": {
        "wkid": 27700,
        "latestWkid": 27700
    },
    "candidates": [
        {
            "address": "CONFERENCE CENTRE, 35 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AA",
            "location": {
                "x": 528352,
                "y": 181795
            },
            "score": 100,
            "attributes": {
                "Match_addr": "CONFERENCE CENTRE, 35 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AA",
                "Addr_type": "Address",
                "LOCATOR_ENVELOPE": "528352,181795,528352,181795",
                "LOCATOR_POINT": "528352,181795",
                "LOCATOR_DESCRIPTION": "CONFERENCE CENTRE, 35 MARYLEBONE HIGH STREET, LONDON, CITY OF WESTMINSTER, W1U 4AA",
                "LOCATOR_FAMILY_ID": "10033572222",
                "LOCATOR_ID": "21770",
                "LOCATOR_DATASET_ID": "5990L000144686:ENG",
                "LOCATOR_DATASET_FAMILY_ID": "10033572222",
                "LOCATOR_RESOLUTION": 90,
                "LOCATOR_SCORE": 100,
                "UPRN": "10033572222",
                "BLPU_LOGICAL_STATUS": 1,
                "BLPU_STATE": 2,
                "BLPU_STATE_DATE": "29/12/2005 00:00:00",
                "PARENT_UPRN": "",
                "RPA": 1,
                "LOCAL_CUSTODIAN_CODE": 5990,
                "BLPU_START_DATE": "29/12/2005 00:00:00",
                "BLPU_END_DATE": null,
                "BLPU_LAST_UPDATE_DATE": "29/12/2005 00:00:00",
                "BLPU_ENTRY_DATE": "29/12/2005 00:00:00",
                "ORGANISATION": "",
                "BLPU_CLASS": "U",
                "WARD_CODE": "",
                "PARISH_CODE": "",
                "BLPU_CUSTODIAN_ONE": null,
                "BLPU_CUSTODIAN_TWO": null,
                "LPI_KEY": "5990L000144686",
                "LPI_LANGUAGE": "ENG",
                "LPI_LOGICAL_STATUS": 1,
                "LPI_START_DATE": "29/12/2005 00:00:00",
                "LPI_END_DATE": null,
                "LPI_LAST_UPDATE_DATE": "29/12/2005 00:00:00",
                "LPI_ENTRY_DATE": "29/12/2005 00:00:00",
                "SAO_START_NUMBER": "",
                "SAO_END_NUMBER": "",
                "SAO_START_SUFFIX": "",
                "SAO_END_SUFFIX": "",
                "SAO_TEXT": "",
                "PAO_START_NUMBER": "35",
                "PAO_END_NUMBER": "",
                "PAO_START_SUFFIX": "",
                "PAO_END_SUFFIX": "",
                "PAO_TEXT": "CONFERENCE CENTRE",
                "LEVEL": "",
                "POSTALLY_ADDRESSABLE": "Y",
                "POSTCODE": "W1U 4AA",
                "POST_TOWN": "LONDON",
                "OFFICIAL_FLAG": "Y",
                "LPI_CUSTODIAN_ONE": null,
                "LPI_CUSTODIAN_TWO": null,
                "STREET_RECORD_TYPE": 1,
                "SWA_ORG_REF_NAMING": 5990,
                "STREET_STATE": null,
                "STREET_STATE_DATE": null,
                "STREET_SURFACE": null,
                "STREET_CLASSIFICATION": null,
                "STREET_VERSION": 0,
                "STREET_LAST_UPDATE_DATE": "27/04/2003 00:00:00",
                "STREET_START_DATE": null,
                "STREET_END_DATE": null,
                "STREET_TOLERANCE": 1,
                "STREET_START_X": 528350,
                "STREET_START_Y": 181538,
                "STREET_END_X": 528365,
                "STREET_END_Y": 182083,
                "STREET_DESCRIPTOR": "MARYLEBONE HIGH STREET",
                "LOCALITY_NAME": "",
                "ADMINISTRATIVE_AREA": "CITY OF WESTMINSTER",
                "TOWN_NAME": "LONDON",
                "STREET_LANGUAGE": "ENG",
                "USRN": "8401405"
            }
        }
    ]
};